### ISSUE TITLE
Fix release workflow

### ISSUE THREAD

**Issue by airibarne** [dribia/driviz#12]
Release workflow trigger should be:

```yaml
on:
  push:
    branches:
      - main
```

Instead of:

https://github.com/dribia/driviz/blob/3e4afba2165f98e7c5b8c4cff8b7db39855891fa/.github/workflows/release.yml#L3-L8
